export const SET_BASE_CURRENCY = 'SET_BASE_CURRENCY';

export const GET_CURRENCY_LIST = 'GET_CURRENCY_LIST';
export const GET_CURRENCY_LIST_DONE = 'GET_CURRENCY_LIST_DONE';
export const GET_CURRENCY_LIST_ERROR = 'GET_CURRENCY_LIST_ERROR';

export const GET_CONVERSION_MAP = 'GET_CONVERSION_MAP';
export const GET_CONVERSION_MAP_DONE = 'GET_CONVERSION_MAP_DONE';
export const GET_CONVERSION_MAP_ERROR = 'GET_CONVERSION_MAP_ERROR';
